version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: shortener-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: shortener-redis
    ports:
      - "6379:6379"

volumes:
  pgdata: